# taken from
# https://www.thenegation.com/posts/pomodoro-waybar-uair/
[defaults]
format = "{time}\n"
paused_state_text = "paused"
resumed_state_text = "resumed"

[[sessions]]
id = "quick"
name = "Quick"
duration = "15m"
time_format = "%M:%S"
command = "notify-send 'Quick Done!'"

[[sessions]]
id = "work"
name = "Work"
duration = "52m"
time_format = "%M:%S"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "17m"
time_format = "%M:%S"
command = "notify-send 'Rest Done!'"

