# taken from
# https://www.thenegation.com/posts/pomodoro-waybar-uair/
# "man 5 uair" for config options

loop_on_end = true

[defaults]
format = "{time}\n"
paused_state_text = "paused"
resumed_state_text = "resumed"

[[sessions]]
id = "work"
name = "Work"
duration = "52m"
time_format = "%M:%S"
command = "notify-send 'Work Done!'"

[[sessions]]
id = "shortwork"
name = "Short Work"
duration = "30m"
time_format = "%M:%S"
command = "notify-send 'Short Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "17m"
time_format = "%M:%S"
command = "notify-send 'Rest Done!'"

