[env]
# Prevent claude from warning about being installed at the system level
DISABLE_INSTALLATION_CHECKS = "1"
DISABLE_AUTOUPDATER = "1"

[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_light.toml"
]

[scrolling]
multiplier = 11

[window]
padding = { x = 5, y = 5 }

[font]
size = 12.0

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]
